parameters:
    mail_manager.class: fibe\CommunityBundle\Services\MailManager
    person_service.class: fibe\CommunityBundle\Services\PersonService
    organization_version_service.class: fibe\CommunityBundle\Services\OrganizationVersionService
services:

    fibe.mail_manager:
        class:  "%mail_manager.class%"
        parent: fos_user.mailer.twig_swift
        calls:
            - [setFrontEndPath, ["?%front_end_path%"]]
            - [setConfirmPath, ["%front_end_confirm_path%"]]


    fibe.PersonService:
        class:  "%person_service.class%"
        parent: fibe.rest.business_service
        arguments: ["@fibe_security.acl_user_permission_helper", "@security.context", "@fos_user.user_manager", "@fos_user.util.token_generator", "@fibe.mail_manager", "@session"]

    fibe.OrganizationVersionService:
        class:  "%organization_version_service.class%"
        parent: fibe.rest.business_service