parameters: 


    routing_dev_file:  routing_dev.yml

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt

    bootstrap_source:  http://twitter.github.com/bootstrap/assets/bootstrap.zip
    max_per_page:      20

    path_to_node:      /usr/local/bin/node

    session.storage.filesystem.class: fibe\RestBundle\Session\Storage


    # social account
    twitter.client_id:      7Z1ShX6LJU7HfS0ewt5gaEovC
    twitter.client_secret:  zAXNt8YIcCWPBqnEjp5StAxtsGDBXg9Gyi3rjoamHijvFkNAGl
    twitter.access_token:   2837911905-RIIPmtyYJaVKmzGorJ8K7ipvGesAzRpzIHT6AC7
    twitter.access_token_secret:    SnUIh0DAiih1gOcj1CmlUe6E9DirwQQrfqWxXPCyEPSur

    social_networks:
        google:
            type:                google
            client_id:           7291802335-siqu12kucgd89889v5g5u0mpnd4nf2ff.apps.googleusercontent.com
            client_secret:       go7GBtGXWM8B1csxPOhC_Gbk
            scope:               "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"  
            options:
                 access_type:     offline 
                 approval_prompt: force
                 display:         popup
                 login_hint:      email address
        twitter:
            type:                twitter
            client_id:           %twitter.client_id%
            client_secret:       %twitter.client_secret%
        facebook:
            type:                facebook
            client_id:           302138773286062
            client_secret:       2ff19b48db1508de43e56be63525d0e4 
            scope:               "email"
            options:
                 display:         popup

        linkedin:
            type:                linkedin
            client_id:           77t2v9vcniqt0s
            client_secret:       MvFQtxReXq2eS7pB